### ISSUE TITLE
Redundant Chat Subscriptions

### ISSUE THREAD

**Issue by AlgosGitHub** [AlgosGitHub/KindleTwitchController#23]
Every connection from the frontend results in a new twitch chat subscription on the backend.

**Comment by MarioMottl** [comment]
Bug is fixed with PR: https://github.com/AlgosGitHub/KindleTwitchController/pull/36

 * Changes Made:
    - Introduced TwitchChannelManager class to handle chat subscriptions.
    - Modified addConnection method to keep track of WebSocket connections for each channel.
    - Implemented removeConnectionFromAllChannels method to remove connections and unsubscribe from the channel when no connections are present.
     - Modified initiateChatSubscription method to initiate chat subscription only if it's not already present for the channel.
